version: "3.9"

services:
  app:
    restart: always

    environment:
      TZ: "Europe/Moscow"

    #    env_file:
    #      - .env

    volumes:
      - ./:/var/www/:rw

    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    expose:
      - 9000
    ports:
      - "80:80"